### ISSUE TITLE
getResult() throws an error if result is undefined

### ISSUE THREAD

**Issue by isaacgr** [isaacgr/jaysonic#45]
`TypeError: Cannot read property 'then' of undefined
[1]     at /mnt/c/Users/irowell/Documents/github/jsonrpc-client/node_modules/jaysonic/lib/server/index.js:300:29
[1]     at new Promise (<anonymous>)
[1]     at WSServer.getResult (/mnt/c/Users/irowell/Documents/github/jsonrpc-client/node_modules/jaysonic/lib/server/index.js:286:14)
[1]     at /mnt/c/Users/irowell/Documents/github/jsonrpc-client/node_modules/jaysonic/lib/ServerProtocol.js:97:30`

**Comment by isaacgr** [comment]
Add tests for this.

**Comment by isaacgr** [comment]
Fixed in #49
