### ISSUE TITLE
TCP client throws error when trying to write after server disconnects

### ISSUE THREAD

**Issue by isaacgr** [isaacgr/jaysonic#7]
Below error appears to be caused by trying to write to the server before its up. This should be handled more gracefully.
`[1] (node:1448) UnhandledPromiseRejectionWarning: Error: This socket has been ended by the other party
[1]     at Socket.writeAfterFIN [as write] (net.js:393:12)
[1]     at /mnt/c/Users/irowell/Documents/stash/media-connect-concept/node_modules/jaysonic/lib/client/tcp.js:123:27
[1]     at new Promise (<anonymous>)
[1]     at Object.send (/mnt/c/Users/irowell/Documents/stash/media-connect-concept/node_modules/jaysonic/lib/client/tcp.js:116:18)
[1]     at Promise (/mnt/c/Users/irowell/Documents/stash/media-connect-concept/server/api/resources.js:36:8)
[1]     at new Promise (<anonymous>)
[1]     at getSites (/mnt/c/Users/irowell/Documents/stash/media-connect-concept/server/api/resources.js:33:10)
[1]     at Socket.client.on (/mnt/c/Users/irowell/Documents/stash/media-connect-concept/server/server.js:50:5)
[1]     at Socket.emit (events.js:189:13)
[1]     at /mnt/c/Users/irowell/Documents/stash/media-connect-concept/node_modules/socket.io/lib/socket.js:528:12
[1] (node:1448) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which wh was not handled with .catch(). (rejection id: 8)`

**Comment by isaacgr** [comment]
Fixed with #12
